### ISSUE TITLE
Predict the next five data points

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/Graph-Analyzer#1]
## Description: 

We need to define and implement a function that can predict the next five data points from the given graph input. 

## Tasks:

1. Define and complete the function predict_next_five_values in analyzer/extract_graph_data.py.
2. Use appropriate algorithms to analyze the graph data and predict the next five values based on the current trend (you can get the data points extracted from the graph using the extract_graph_data function)
3. Call the predict_next_five_values function in analyzer/views.upload_image.
4. Modify the frontend to display the predicted next five values on the homepage after the image upload.

## Expected Outcome:

The next five predicted values should be displayed on the homepage, providing insights based on the graph data.

**Comment by anushkaVerma1007** [comment]
Ma'am, I am interested ..please assign this issue to me.

**Comment by sahaj-96** [comment]
Ma'am, I am interested

**Comment by RITIK-CHAUDHRY** [comment]
@Nandika-A mam i have requested to contrihub please assign me this issue so that i can start working on this

**Comment by RITIK-CHAUDHRY** [comment]
@Nandika-A mam if someone else is working or completed please close my request on contrihub as theni can apply to other
