### ISSUE TITLE
Expand Graph Analysis Capabilities

### ISSUE THREAD

**Issue by Nandika-A** [ContriHUB/Graph-Analyzer#3]
## Description: 
Currently, the graph analysis functionality is limited to finding maxima and minima. We need to enhance this feature by implementing additional graph analysis techniques to provide more insights and data interpretation.

## Tasks:

1. Identify and define additional graph analysis methods (e.g., trend analysis, inflection points, derivatives).
2. Implement the chosen methods in the existing graph analysis module (e.g., analyzer/extract_graph_data.py).
3. Ensure that the new analysis methods can be integrated into the existing workflow seamlessly.
4. Update the documentation to reflect the new functionalities and how to use them.

**Comment by aachintya** [comment]
Hello ma'am requested for the issue

**Comment by RITIK-CHAUDHRY** [comment]
@Nandika-A mam i have requested to contrihub please assign me this issue
